service: aws-node-express-dynamodb-api

frameworkVersion: "3"

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [UsersTable, Arn]
  environment:
    USERS_TABLE: users-table-${self:provider.stage}

functions:
  api:
    handler: ./packages/server-lambda/src/handler.handler
    events:
      - httpApi: "*"

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: users-table-${self.provider.stage}

plugins:
  - serverless-offline
  - serverless-dynamodb-local
  - serverless-esbuild
# - serverless-plugin-typescript
